version: '3.8'
services:
  web:
    container_name: fastApi
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - static_vol:/code/static
      - media_vol:/code/media

  nginx:
    container_name: nginx
    image: nginx:1.23.1
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/code
      - static_vol:/code/static
      - media_vol:/code/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
volumes:
  static_vol:
  media_vol: